### ISSUE TITLE
Don't use List in persisters

### ISSUE THREAD

**Issue by RayRoestenburg** [scalapenos/stamina#6] opened 2015-02-08 17:03 UTC
But choose a faster data structure, this is going to be hot path code. you could even just generate a unique token from the Persisted and put it in a map for direct access (since you find first anyway).

**Comment by agemooij** [comment] 2015-02-08 17:29
Good idea. As long as the result stays composable any internal data structure should do. I'll look into using a Map.

**Comment by agemooij** [comment] 2015-02-08 21:52
The only operations in the hot path are traversal (i.e. `find()`) and AFAIK Vector has similar, if not equal, performance for pure traversal. I might be wrong here but I couldn't find anything on traversal performance comparisons here: http://docs.scala-lang.org/overviews/collections/performance-characteristics.html

A Map will be hard because I would have to know the set of all possible arguments to `persist` up front. I will only know whether a contained persister can persist this class when I find one that does, right?

Of course all of this is caused by Akka's insistence on using AnyRef as the argument type to `toBinary`. This was the best way around that I have found so far.

What am I missing?

**Comment by agemooij** [comment] 2015-02-08 21:57
I guess if I would change the API to register instances of `Persister` one by one I could extract `ClassTag`s and build up some kind of lookup table based on the runtime `Class` (for persistence only) and an approximate subset of potentially supporting persisters based on the registered key (for unpersisting). 

Definitely food for thought, but I'm not going there until I get some micro-benchmarking code in place ;)

**Comment by RayRoestenburg** [comment] 2015-02-08 22:23
Ah right, the AnyRef. you could just blow it up at persist (no checking,
just throw Unregistered where you now throw IllegalArgumentException) and
just using s"$key::$version" as key in the Map (which you can use for
canUnpersist?)

**Comment by agemooij** [comment] 2015-02-08 22:36
Nope, `s"$key::$version"` won't work beyond V1 since V2+ persisters are always forced to be able to unpersist all previous versions, at least that constraint is currently in place for the json implementation. 

But a key-only Map lookup would provide an Option without having to traverse a List or Vector. that `Option` is enough to then call `canUnpersist` on.

I'm not sure what you mean by "you could just blow it up at persist (no checking,
just throw `Unregistered` where you now throw `IllegalArgumentException`)".  AFAIK there are no `IllegalArgumentException`s thrown in `Persisters.scala`...

Could you be a bit more specific on what you suggest?

**Comment by RayRoestenburg** [comment] 2015-02-09 09:07
yes so key would actually be enough. Never mind the IllegalArgumentException bit, that didn't make sense after all. so for persist you got a problem because of any. Unless you say "well I'm just going to try and cast it to the stamina base trait if you are using StaminaSerializer anyway, if the cast works I'll use the map, otherwise I'll have to run through the map values"

**Comment by agemooij** [comment] 2015-07-29 09:14
Closing for now.

**Closed as completed by agemooij** 2015-07-29 09:14 UTC
